import "./globals.css";
import ProviderComponent from "@/components/ProviderComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <ProviderComponent>
    <body>{children}</body>
    </ProviderComponent>
    </html>
  );
}
